-- إنشاء الجداول لـ Supabase (PostgreSQL)

-- جدول المستخدمين
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  openId VARCHAR(64) NOT NULL UNIQUE,
  name TEXT,
  email VARCHAR(320),
  loginMethod VARCHAR(64),
  role VARCHAR(20) DEFAULT 'user' NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  lastSignedIn TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- جدول المديرين
CREATE TABLE IF NOT EXISTS admin_users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'admin' NOT NULL,
  isSuperAdmin INTEGER DEFAULT 0 NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- جدول طلبات التسجيل
CREATE TABLE IF NOT EXISTS registrations (
  id SERIAL PRIMARY KEY,
  offerIndex INTEGER NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(320),
  notes TEXT,
  status VARCHAR(20) DEFAULT 'pending' NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- جدول طلبات الشهادات
CREATE TABLE IF NOT EXISTS certificate_requests (
  id SERIAL PRIMARY KEY,
  courseName VARCHAR(255) NOT NULL,
  fullNameAr VARCHAR(255) NOT NULL,
  fullNameEn VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  birthPlace VARCHAR(255) NOT NULL,
  birthDate VARCHAR(50) NOT NULL,
  gender VARCHAR(20) NOT NULL,
  idCardUrl VARCHAR(500),
  grades JSONB,
  finalGrade VARCHAR(50),
  average VARCHAR(50),
  total VARCHAR(50),
  status VARCHAR(20) DEFAULT 'pending' NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
